# Generated by Django 3.1 on 2020-08-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200830_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='protected',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
