# Generated by Django 3.1 on 2020-08-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tweet_is_poll_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
    ]
