# Generated by Django 3.1 on 2020-08-30 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tweet_is_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='registered_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registering_tweets', to='main.twitteruser'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='main.twitteruser'),
        ),
    ]
