version: '3'
services:
  app:
    build: .
    # command: bash -c "sleep 1s && python3 manage.py runserver 0.0.0.0:8000"
    command: gunicorn -w 4 Nalypoll.wsgi -b 0.0.0.0:8000
    restart: always
    ports:
      - 8002:8000
    volumes:
      - ./Nalypoll:/code
    env_file:
      - .env.django
    depends_on:
      - db
  updater:
    build: .
    command: bash -c "sleep 1s && python3 tools/PollUpdater.py"
    restart: always
    volumes:
      - ./Nalypoll:/code
    env_file:
      - .env.django
    depends_on:
      - db
  db:
    image: mariadb:10.4
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .env.mysql
