# Generated by Django 3.1 on 2020-08-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200830_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='access_token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='access_token_secret',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='authorized_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='checked_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='last_access_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
