# Generated by Django 3.1 on 2020-08-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200831_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='is_registered',
        ),
    ]
