# Generated by Django 3.1 on 2020-08-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_twitteruser_protected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitteruser',
            old_name='authorized_at',
            new_name='token_saved_at',
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='protected',
            field=models.BooleanField(null=True),
        ),
    ]
